// <auto-generated />
using System;
using BancoDigital.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BancoDigital.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BancoDigital.API.Domain.Entities.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("AGENCIAS", (string)null);
                });

            modelBuilder.Entity("BancoDigital.API.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenciaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<int>("TIPO_CLIENTE")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("CLIENTES", (string)null);

                    b.HasDiscriminator<int>("TIPO_CLIENTE");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BancoDigital.API.Domain.Entities.Contratacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("MotivoStatus")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int?>("PrazoMeses")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ScoreCalculado")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal?>("TaxaJurosAplicada")
                        .HasColumnType("NUMBER(9,4)");

                    b.Property<decimal?>("ValorAprovado")
                        .HasColumnType("NUMBER(18,2)");

                    b.Property<decimal>("ValorSolicitado")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("CONTRATACOES", (string)null);
                });

            modelBuilder.Entity("BancoDigital.API.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<string>("TIPO_PRODUTO")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)");

                    b.HasKey("Id");

                    b.ToTable("PRODUTOS", (string)null);

                    b.HasDiscriminator<string>("TIPO_PRODUTO").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BancoDigital.API.Domain.Entities.PessoaFisica", b =>
                {
                    b.HasBaseType("BancoDigital.API.Domain.Entities.Cliente");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("RendaMensal")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("\"Cpf\" IS NOT NULL");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("BancoDigital.API.Domain.Entities.PessoaJuridica", b =>
                {
                    b.HasBaseType("BancoDigital.API.Domain.Entities.Cliente");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("FaturamentoMensal")
                        .HasColumnType("NUMBER(18,2)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("\"Cnpj\" IS NOT NULL");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("BancoDigital.API.Domain.Entities.Emprestimo", b =>
                {
                    b.HasBaseType("BancoDigital.API.Domain.Entities.Produto");

                    b.Property<int>("PrazoMaximoMeses")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("TaxaJurosBaseAoMes")
                        .HasColumnType("NUMBER(9,4)");

                    b.Property<decimal>("ValorMaximo")
                        .HasColumnType("NUMBER(18,2)");

                    b.Property<decimal>("ValorMinimo")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasDiscriminator().HasValue("EMPRESTIMO");
                });

            modelBuilder.Entity("BancoDigital.API.Domain.Entities.MaquinaDeCartao", b =>
                {
                    b.HasBaseType("BancoDigital.API.Domain.Entities.Produto");

                    b.Property<decimal>("AluguelMensal")
                        .HasColumnType("NUMBER(18,2)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<decimal>("TaxaMdrCredito")
                        .HasColumnType("NUMBER(9,4)");

                    b.Property<decimal>("TaxaMdrDebito")
                        .HasColumnType("NUMBER(9,4)");

                    b.HasDiscriminator().HasValue("MAQUINA_CARTAO");
                });

            modelBuilder.Entity("BancoDigital.API.Domain.Entities.ReceberSalario", b =>
                {
                    b.HasBaseType("BancoDigital.API.Domain.Entities.Produto");

                    b.Property<string>("CnpjEmpregador")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)");

                    b.Property<string>("EmpresaConveniada")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasDiscriminator().HasValue("RECEBER_SALARIO");
                });

            modelBuilder.Entity("BancoDigital.API.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("BancoDigital.API.Domain.Entities.Agencia", "Agencia")
                        .WithMany("Clientes")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("BancoDigital.API.Domain.Entities.Contratacao", b =>
                {
                    b.HasOne("BancoDigital.API.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Contratacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BancoDigital.API.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BancoDigital.API.Domain.Entities.Agencia", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("BancoDigital.API.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Contratacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
